# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Grepai < Formula
  desc "Privacy-first semantic code search CLI"
  homepage "https://github.com/Slicit/grepai"
  version "0.1.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Slicit/grepai/releases/download/v0.1.9/grepai_0.1.9_darwin_amd64.tar.gz"
      sha256 "c8f00a1c870840cca1a709c6b1aaea07a4f4bde145f465f2c2618fba7f618f64"

      define_method(:install) do
        bin.install "grepai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Slicit/grepai/releases/download/v0.1.9/grepai_0.1.9_darwin_arm64.tar.gz"
      sha256 "35ea0afbc120c0e96a0c5fca87bdebb2a148cd226c4e3083c11a4babcbf05ab1"

      define_method(:install) do
        bin.install "grepai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Slicit/grepai/releases/download/v0.1.9/grepai_0.1.9_linux_amd64.tar.gz"
      sha256 "8c21fc265bcceb692bf09a3f24273110b3352e4bc4bc09064f6fc511a06f51eb"
      define_method(:install) do
        bin.install "grepai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Slicit/grepai/releases/download/v0.1.9/grepai_0.1.9_linux_arm64.tar.gz"
      sha256 "3b0ba5ccf529364cecfa61713d65d052da4b55e07df0fea543b89e7919a3fbca"
      define_method(:install) do
        bin.install "grepai"
      end
    end
  end

  test do
    system "#{bin}/grepai", "--version"
  end
end
